# Generated by Django 6.0.6 on 2026-08-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
