# Generated by Django 6.0.6 on 2026-08-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
