# Generated by Django 6.0.6 on 2026-08-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shop', '0004_openinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shops',
            field=models.ManyToManyField(blank=True, to='shop.shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
